### ISSUE TITLE
Write spec for logging framework

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/corto#136]
Why the spec'ing? Well, for one part it doesn't just print messages anymore:
- They can be embedded into other messages (sic.)
Proposals:
- Messages included the logging level by default (e.g. "error", "warning", "info", "debug").
- Logging levels are customizable.
- Output streams are customizable and can be multiple for a logging level (e.g. console, file, email).
- Messages can be grouped, e.g. when logging about the contents of a folder, each file is displayed in a single line, but they are not preceded by the logging level name.
- Log messages can be formatted for a particular logger as desired, e.g. `"$level [$timestamp]: $message"`.

Message logging can be as easy as using a default logger, or it can be --in the long run-- heavily configurable.

Now, this is not my brand new ideas... I'm suggesting patterns that I've used when developing web backends, and in my previous experience as a tester.
Check:
- https://docs.djangoproject.com/en/1.7/topics/logging/
- https://docs.python.org/3.4/library/logging.html

**Comment by SanderMertens** [comment]
Can we keep this simple? I'm not sure whether I want to build a full fledged logging framework. Basically because:
1) It's not the most exciting thing in the world
2) It's tricky to make it generic and performant enough

What I would like, is provide the capability to integrate with other logging frameworks. For that, the only thing we would need to provide is a callback mechanism that gets invoked whenever any of the error functions is used.

I would really like to keep this part of the framework as simple as possible.

**Comment by SanderMertens** [comment]
I'm closing this as the error logging has significantly changed since this ticket was opened. If we need a logging framework in the future, we'll write an issue with more specific requirements.
