### ISSUE TITLE
Generator for reference documentation

### ISSUE THREAD

**Issue by SanderMertens** [cortoproject/corto#16]
Since the object store is fully reflective it serves as ideal purpose for generation of reference documentation. Doing so ensures conformity throughout all of the documentation artifacts. It is also a lot less labour intensive to create and (especially) maintain.

A generator for reference documentation would work like a regular code generator and would use the generator API. This has as advantage that the dbgen tool can be used to generate the documentation.

The output of the code generator will be a set of HTML, CSS and possibly JavaScript files that together will form the documentation. At a later point in time generators could be developed that output to different formats but HTML has the widest applicability thus is the preferred format for now.

A good reference for what this could look like is the Qt online reference documentation: http://qt-project.org/doc/qt-5/reference-overview.html

Note that the documentation generated from the object store alone is not sufficient and merely provides the "scaffolding". It should be possible to annotate objects in the store with text to provide more context and explanation. This possibly requires a small extension of the object management, depending on the design.

**Comment by jleeothon** [comment]
This has been largely implemented. Known issues are documented in other tickets, and subsequent bugs should yield new tickets. I'll close this.

**Comment by jleeothon** [comment]
Need to make the output folder specifiable. This is going to be achieved with attributes. By default, the output folder is "doc".
```
cxgen myfile -g html --attr doc=coolDocuments
```

**Comment by jleeothon** [comment]
The following workflow for generating documentation is proposed:

1. User has a package.
2. Package is passed to markdown generator, producing a markdown scaffold (in a .md file).
3. User fills out blanks in the scaffold.
4. Markdown is passed to a parser.
5. Parser generates a "documentation tree" (see below).
6. Documentation tree is turned into HTML.

**Example source code**

```
::MyPackage
  ::FooClass
    ::BarMethod()
    ::NestedClass
```

**Example markdown**

```
# ::MyPackage

This package is cool

## FooClass

This class is *cool*

### BarMethod

This method is called many times, like `this`:
- hey
- yey

## FooClass::NestedClass

This class is nested
```

**Example doc tree**

```
::DocumentationScope
    ::MyPackage (PackageDoc)
      ::paragraph1 (DocParagraph): "This package is cool"
      ::FooClass (ClassDoc)
        ::paragraph1 (DocParagraph): "This class is *cool*" <-- notice we don't have an *emphasis* Corto object
        ::BarMethod (MethodDoc)
          ::paragraph1: "This method is called many times, like `this`" <- no code span
          ::list1::
            ::listElem1: "hey"
            ::listElem2: "yey"
        ::NestedClassDoc (ClassDoc)
          ::paragraph1: "This class is nested"
```

**Example HTML**

Looks almost the same as just parsing the markdown, except that because we can enrich the documentation tree with extra information, we can do other cool things like links to the documented classes/methods/etc.
