### ISSUE TITLE
Object annotations

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/corto#169]
Several ideas that we want to implement would be well served of object annotations:
- Documentation (think, Javadoc, Docstring, etc.)
- Interfaces, for example to override or disambiguate object names in all sorts of bindings.
# In source code
## Proposal 1

Define a grammar rule for annotations.

For example (just an example!):

```
class Dog::
    // <doc>
    // Well... barks.
    // <doc>
    // <cinterface>
    // goTo
    // </cinterface>
    void goto(string place):
        "I just got to $place"
```
## Proposal 2

Define an Annotation class that binds an object to a string. It is fed to whomever needs it, e.g. the interfaces or serializers or database managers.

```
// animals.cx
class Dog::
    void goto(string place):
        "I just got to $place"

// animal-cbinding.cx
list{NameBinding} bindings {
    {::Dog, "Dog"},
    {::Dog::goto, "goTo"}
}
```

Then we can run:

```
cxgen animals.cx --lang c --annotations animal-cbinding.cx
```
## Analysis

Solution 1 is be better for documentation.
It is also more comfortable and faster to write.

Solution 2 has broader range of uses.
If we solely stuck to Solution 1, for example, what if someone writes LibraryA that was not thought for to be serialized to language X and its imcompatible (e.g. uses a keyword)? Then because we might only have the binaries installed for the libraries, we will not be able to include it in a bound system.
# Internal representation

There was some debate among @cortexlang/owners on how to represent them:
- on how they apply to objects:
  - same annotations for every object
  - different annotations per object.
- on how they should be stored:
  - A priority queue (over a list)
  - A map (RB tree).
  - An ordered array
## Universality of annotations

There are some cases where annotations are desired for _every_ object in the store, for example, guilds.

There are other cases where annotations are only required for certain objects, for example to store binding names of class objects; or as would benefit sqlite to store prepared INSERT statements.

While some performance could be boosted if we require all objects in the store to implement the same objects, the space (extra memory) and time (update all objects' annotation collections) make it inappropriate.

The analysis below on data structures considers that every object has its own annotations even if a name could be repeated everywhere in the 
### Priority queue

Linear insertion, linear query.
### Map

If implemented using Cortex's RB Tree:
Logarithmic insertion, logarithmic search. More space consuming.
### Ordered array

Assuming that `qsort` and `bsearch` is used for ordering and querying...
Insertion time for quicksort is O(n^2), but that case is said to be rare (also, we always have almost-ordered arrays). Average case is said to be linear-logarithmic. Query time is logarithmic, as is a strict map's. Probably less space consuming than a map tree.
However, a key-value pair struct is also required (so to use string indices).
### Conclusion

We go for an ordered array.

**Comment by jleeothon** [comment]
@SanderMertens please confirm if you agree.

**Comment by SanderMertens** [comment]
I would like to see proposal one and two combined. Suppose we create a new type called 'annotation'. Lets define it like this (using a slightly modified version of the design pattern we used for delegates):
```
class annotationData::
    object : object // The object to annotate

class annotation : struct::
    type : type // Specifies the type of objects for this annotation
    int16 construct(): 
        this.base = annotationData
        // A bit of metaprogramming creating a new member 'data' holding annotation data
        member(this.declare("data", member)) = {this.type}
```
We can then use this class to create a new annotation type
```
annotation doc: type = string
```
And then use this new annotation type like this to annotate an object:
```
class Dog::
    void bark(): "Bark Bark"

doc{Dog::bark, "Make it bark"}
```
This would however force putting the annotation after an object is declared, which is not as nice. We could add additional logic that, when an annotation is created and the `object` member is left to `null`, we will "stage" the annotation and apply it to the first object that is created, like this:
```
doc{data = "A dog-spawning class"}
class Dog::
    doc{data = "Make it bark"}
    void bark(): "Bark Bark"
```
This looks better. 

Note that I'm creating anonymous objects here. Because I'm not assigning the objects, they will be destroyed immediately after creation. That is ok. They are just meant to call a core 'annotation API' that attaches the 'data' member to an object.

If we'd like, we can always add additional syntactic sugar like you suggested above (I would use a syntax similar to Java annotations):
```
@doc("A dog-spawning class")
class Dog::
    @doc("Make it bark")
    void bark(): "Bark Bark"
```
