### ISSUE TITLE
Corto_Resolve for "foo/sander/sander" returns parent object

### ISSUE THREAD

**Issue by hendrenja** [cortoproject/corto#535]
When trying to resolve a child with the same name as the parent, the parent object is returned. 

Lookup for inputchecker/input/0/0 returns the object "inputchecker/input/0".

Address of parent 34000625160  
Address of retObj 34000625160

**Comment by SanderMertens** [comment]
This only happens when `inputchecker/0/0` does not exist. When `corto_resolve` doesn't find an object, it will automatically try to find the identifier while traveling up in the hierarchy. The algorithm is comparable to when you lookup an identifier in C++. If you cannot find it in the current namespace, try the parent namespace.

The following code illustrates this behavior:
```
    corto_object a = corto_voidCreateChild(root_o, "a");
    corto_object resolved_1 = corto_resolve(a, "a");

    corto_voidCreateChild(a, "a");
    corto_object resolved_2 = corto_resolve(a, "a");

    printf("resolved_1 = %s, resolved_2 = %s\n",
      corto_fullpath(NULL, resolved_1),
      corto_fullpath(NULL, resolved_2));
```

This yields:
```
resolved_1 = /a, resolved_2 = /a/a
```

If you don't want this behavior (going up scopes until the object is found), use `corto_lookup`. When replacing `corto_resolve` with `corto_lookup` in the above code, the output looks like this:
```
resolved_1 = , resolved_2 = /a/a
```

**Comment by rfloresx** [comment]
Reading on the doc, `corto_lookup` won't interrogate mounts. And `corto_resolve` first will look in `/corto/lang` then `scope`/`corto_lookup` then on the mount. 

Is there a method similar to `corto_lookup` that interrogate mounts?

I can see few issue using `corto_resolve` in our main object stores, we have multiple mounts in our object store that needs to interrogate the mount,  The mount is not guarantee that will have the requested object. I use `corto_resolve` check if return `NULL` to insert a new object to the `data store` / `mount`. 
Example: 
If I have a object store with the following data: 
```
Net    //Net Is a mount 
    Devices
        One
            Input
                One  
                //Net mount does not have `Two` will return null. 
        Two
            Output
                One 
                Two
```
And if we want to insert a new object using the following method: `GetInputAuto(Input_o, "Two");`
```
corto_object GetInputAuto(corto_object parent, corto_string name) { 
    corto_object obj = corto_resolve(parent, name);
    if (obj == NULL) {
        obj = CreaeObject(parent,  name);
    }
   return obj;
}
```
`corto_resolve` will return the `Two` object from `Devices` and `corto_lookup` won't work in this case because I need it to ask the `mount` if it have the object.

**Comment by SanderMertens** [comment]
@rfloresx I was just thinking about that when I wrote my previous reply. The current design isn't orthogonal (`corto_resolve` does two things more than `corto_lookup` where you maybe only want one).

As mounts are supposed to be a transparent mechanism, I think the best solution to this is to make  `corto_lookup` interrogate mounts as well (instead of introducing yet another function).

BTW, your last example, where you first resolve an object and then create it when it doesn't exist, contains a race condition (what if the object is created between `corto_resolve` and `CreateObject`).

It is better to write that code like this:
```c
    corto_object obj = corto_declare(parent, name);
    if (!corto_checkState(obj, CORTO_DEFINED)) {
        // set members, etc.
        corto_define(obj);
    }
```
The above code is thread safe, as `corto_declare` will never return an undefined object when the object is not declared in your own thread.
