### ISSUE TITLE
Generate rakefile from package.json

### ISSUE THREAD

**Issue by jleeothon** [cortoproject/corto#571]

**Comment by SanderMertens** [comment]
First implementation uses a big package type that contains both package information parameters and buildsystem parameters. Mixing these settings is not nice, because many settings from the buildsystem are specific to a language / compiler, and packages can be written in many different languages.

A mechanism needs to be provided whereby the buildsystem can determine at runtime which toolchain is required for the package, and only accept parameters in `project.json` specific to that toolchain. That way, a `project.json` for a C project will have different members than, for example, a `python` project.

This same mechanism should also allow specifying parameters for custom components, like using lex/yacc or a custom library/preprocessor.
